### ISSUE TITLE
replace the term Policy by Rulebook to avoid confusion?

### ISSUE THREAD

**Issue by mielvds** [MellonScholarlyCommunication/spec-orchestrator#6]
@phochste @Dexagod @JWerbrouck I'd like a resolution on the name 'Policy', because changing it everywhere will become more and more difficult.

**Comment by phochste** [comment]
I've come up with other terminology but nothing really sticks

- Plan
- Bundle 
- Actions
- Tasks
- Rule Set

Rulebook is a good choice. 

As context, the term *Policy* is problematic because it suggest much more than what Orchestrator does. It is a university policy that published artifacts need to be in the institutional registration hub. This policy can lead to a rulebook where a researcher get the suggestion to deposit a publication. A rulebook is a machine actionable set of rules that **could** implement a policy of a organisation. We don't have the intention to codify organisation policies (annotating policy documents into triples).

**Comment by mielvds** [comment]
I agree and also thanks for suppying us with the definition "A rulebook is a machine actionable set of rules that could implement a policy of a organisation. " :)

**Comment by Dexagod** [comment]
:+1: on rulebook
